# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='answer_comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=12)),
                ('comment', models.CharField(max_length=100)),
                ('answer_id', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=12)),
                ('answer', models.CharField(max_length=1000)),
                ('question_id', models.CharField(max_length=3)),
                ('vote', models.CharField(max_length=3)),
                ('date', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=20)),
                ('question_head', models.CharField(max_length=100)),
                ('question_detail', models.CharField(max_length=1000)),
                ('vote', models.CharField(max_length=3)),
                ('date', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='question_comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=12)),
                ('comment', models.CharField(max_length=100)),
                ('question_id', models.CharField(max_length=3)),
            ],
        ),
    ]
