# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer_comments',
            name='cpid',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer_comments',
            name='date',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answers',
            name='cpid',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question_comments',
            name='cpid',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question_comments',
            name='date',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
