# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_answer_comments_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='answer_num',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
