# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_answers_answer_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer_comments',
            name='image',
            field=models.CharField(default='images/images.jpg', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer_comments',
            name='skid',
            field=models.CharField(default=2, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answers',
            name='image',
            field=models.CharField(default='images/images.jpg', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answers',
            name='skid',
            field=models.CharField(default=2, max_length=4),
            preserve_default=False,
        ),
    ]
