# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_auto_20160501_0456'),
    ]

    operations = [
        migrations.CreateModel(
            name='questionlike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=12)),
                ('question_id', models.CharField(max_length=3)),
            ],
        ),
    ]
