# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_questionlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='answerlike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=12)),
                ('question_id', models.CharField(max_length=3)),
                ('answer_num', models.CharField(max_length=3)),
            ],
        ),
    ]
