# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_answerlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerlike',
            name='pid',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='questionlike',
            name='pid',
            field=models.CharField(max_length=40),
        ),
    ]
