# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_auto_20160509_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer_comments',
            name='cpid',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='answers',
            name='cpid',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='question_comments',
            name='cpid',
            field=models.CharField(max_length=40),
        ),
    ]
