# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_id', models.CharField(max_length=6)),
                ('pid', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='workshop_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=12)),
                ('workshop_title', models.CharField(max_length=40)),
                ('workshop_detail', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=100)),
                ('subscriber_num', models.CharField(max_length=4)),
                ('videos_num', models.CharField(max_length=4)),
                ('ratings', models.CharField(max_length=4)),
                ('date', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='workshop_videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_id', models.CharField(max_length=40)),
                ('video', models.FileField(upload_to='videos')),
            ],
        ),
    ]
