# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_auto_20160426_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshop_detail',
            old_name='workshop_detail',
            new_name='workshop_details',
        ),
    ]
