# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_auto_20160426_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='date',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriber',
            name='images',
            field=models.FileField(default='images/images.jpg', upload_to='images'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='ratings',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriber',
            name='subscriber_num',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriber',
            name='videos_num',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriber',
            name='workshop_title',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
