# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0007_workshop_videos_vid_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='workshoplike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_id', models.CharField(max_length=6)),
                ('pid', models.CharField(max_length=40)),
            ],
        ),
    ]
