# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0008_workshoplike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop_detail',
            name='pid',
            field=models.CharField(max_length=40),
        ),
    ]
