# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='imagestore',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video',
            new_name='videostore',
        ),
    ]
