# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20160426_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='testvideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videostore', models.FileField(upload_to='videos')),
                ('idk', models.FileField(upload_to='videos')),
            ],
        ),
    ]
