# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 05:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_testvideo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testvideo',
            old_name='idk',
            new_name='idksi',
        ),
    ]
