# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('f_name', models.CharField(max_length=20)),
                ('l_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=12)),
                ('pin', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=19)),
                ('college', models.CharField(max_length=30)),
                ('biography', models.CharField(max_length=500)),
                ('skills', models.CharField(max_length=10)),
                ('tenthth_marks', models.CharField(max_length=5)),
                ('twelth_marks', models.CharField(max_length=5)),
                ('course', models.CharField(max_length=20)),
                ('pid', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
    ]
