# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='pid',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
