# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsubs',
            name='technology',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
