# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_projectsubs_technology'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_info',
            old_name='image',
            new_name='images',
        ),
    ]
