# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20160429_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_info',
            name='videodate',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
