# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_project_info_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsubs',
            name='name',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectsubs',
            name='profid',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
