# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20160429_0241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsubs',
            name='profid',
        ),
    ]
