# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_remove_project_info_synopsis'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_info',
            name='synopsis',
            field=models.FileField(default='nourl', max_length=500, upload_to='synfiles'),
            preserve_default=False,
        ),
    ]
