# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_project_info_synopsis'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_info',
            name='synopfile',
            field=models.CharField(default='MINOR_REPORT', max_length=80),
            preserve_default=False,
        ),
    ]
