# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_project_info_synopfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_info',
            name='pid',
            field=models.CharField(max_length=50),
        ),
    ]
