# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall_of_fame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill_karma_details',
            name='name',
            field=models.CharField(default='Piyush Sharma', max_length=40),
            preserve_default=False,
        ),
    ]
