# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall_of_fame', '0002_skill_karma_details_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill_karma_details',
            name='spuser',
            field=models.CharField(default='no', max_length=4),
            preserve_default=False,
        ),
    ]
