# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall_of_fame', '0003_skill_karma_details_spuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill_karma_details',
            name='image',
            field=models.CharField(default='images/images.jpg', max_length=50),
            preserve_default=False,
        ),
    ]
