# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall_of_fame', '0004_skill_karma_details_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill_karma_details',
            name='total',
            field=models.IntegerField(),
        ),
    ]
