# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall_of_fame', '0005_auto_20160502_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill_karma_details',
            name='pid',
            field=models.CharField(max_length=40),
        ),
    ]
