# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeration',
            name='id',
        ),
        migrations.AlterField(
            model_name='registeration',
            name='uid',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
