# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0002_auto_20160317_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeration',
            name='isactivate',
            field=models.CharField(default='no', max_length=4),
            preserve_default=False,
        ),
    ]
