# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0003_registeration_isactivate'),
    ]

    operations = [
        migrations.CreateModel(
            name='act_key',
            fields=[
                ('pid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('active_key', models.CharField(max_length=40)),
            ],
        ),
    ]
