# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 22:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0004_act_key'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='act_key',
            new_name='activation_key',
        ),
    ]
