# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 23:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0005_auto_20160319_0429'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='activation_key',
            new_name='activatekey',
        ),
    ]
