# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0006_auto_20160319_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeration',
            name='spuser',
            field=models.CharField(default='no', max_length=4),
            preserve_default=False,
        ),
    ]
