# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0007_registeration_spuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeration',
            name='image',
            field=models.FileField(default='images/images.jpg', upload_to='images'),
            preserve_default=False,
        ),
    ]
