# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0009_remove_registeration_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeration',
            name='dob',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='registeration',
            name='pid',
            field=models.CharField(max_length=19),
        ),
    ]
