# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0010_auto_20160502_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeration',
            name='spcollege',
            field=models.CharField(default='na', max_length=100),
            preserve_default=False,
        ),
    ]
