# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=12)),
                ('title', models.CharField(max_length=100)),
                ('attending', models.CharField(max_length=3)),
                ('detail', models.CharField(max_length=1000)),
                ('date', models.CharField(max_length=10)),
                ('start_time', models.CharField(max_length=10)),
                ('end_time', models.CharField(max_length=10)),
                ('venue', models.CharField(max_length=100)),
                ('notice', models.CharField(max_length=100)),
            ],
        ),
    ]
