# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_joined_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_detail',
            name='image',
            field=models.FileField(default='images/images.jpg', upload_to='images'),
            preserve_default=False,
        ),
    ]
