# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_detail_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_detail',
            old_name='image',
            new_name='images',
        ),
    ]
