# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20160502_0056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_detail',
            old_name='images',
            new_name='image',
        ),
    ]
